version: "3.5"
services:
  placement-api:
    container_name: openstack_placement-api
    image: huynda/openstack_placement-api:yoga
    ports:
      - 10.0.0.1:8778:8778
    environment:
      PROTOCOL: http
      CONTROLLER_IP: 10.0.0.1
      DATABASE_HOST: 10.0.0.1
      MEMCACHED_HOST: 10.0.0.1
      TRANSPORT_URL: rabbit://openstack:XXXXXXXXXXXXXXXXXXXXXX@10.0.0.1
      DATABASE_PASS: XXXXXXXXXXXXXXXXXXXXXX
      PLACEMENT_PASS: XXXXXXXXXXXXXXXXXXXXXX
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/log/apache2:/var/log/apache2
    restart: always

